@@create/create-murm-user.sql
@@create/create-murm-post.sql
@@create/create-murm-vote.sql
@@create/create-murm-share.sql
@@create/create-murm-session.sql
@@create/create-murm-password-reset.sql
@@triggers/tg_murm_user_biu.sql
@@triggers/tg_murm_post_biu.sql
@@triggers/tg_murm_vote_aiud.sql
@@triggers/tg_murm_share_ai.sql
@@indexes/create-murm-indexes.sql
