-- MURMURINHO
-- AJUSTES DO BANCO PARA O MVP COM ORACLE
-- PODE SER EXECUTADO NOVAMENTE SEM DUPLICAR COLUNAS, CONSTRAINTS OU ÍNDICES.


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_tab_columns
    WHERE table_name = 'MURM_USER'
      AND column_name = 'PASSWORD_CHANGED_AT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE murm_user
            ADD password_changed_at TIMESTAMP
        ';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_tab_columns
    WHERE table_name = 'MURM_USER'
      AND column_name = 'THEME_CODE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE murm_user
            ADD theme_code VARCHAR2(10) DEFAULT ''auto'' NOT NULL
        ';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_constraints
    WHERE table_name = 'MURM_USER'
      AND constraint_name = 'CK_MURM_USER_THEME';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE murm_user
            ADD CONSTRAINT ck_murm_user_theme
            CHECK (theme_code IN (''light'', ''dark'', ''auto''))
        ';
    END IF;
END;
/


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_tab_columns
    WHERE table_name = 'MURM_POST'
      AND column_name = 'DELETED_AT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE murm_post
            ADD deleted_at TIMESTAMP
        ';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_tab_columns
    WHERE table_name = 'MURM_POST'
      AND column_name = 'DELETED_BY_USER_ID';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE murm_post
            ADD deleted_by_user_id NUMBER
        ';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_tab_columns
    WHERE table_name = 'MURM_POST'
      AND column_name = 'MODERATED_AT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE murm_post
            ADD moderated_at TIMESTAMP
        ';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_tab_columns
    WHERE table_name = 'MURM_POST'
      AND column_name = 'MODERATION_REASON';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE murm_post
            ADD moderation_reason VARCHAR2(1000)
        ';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_constraints
    WHERE table_name = 'MURM_POST'
      AND constraint_name = 'FK_MURM_POST_DELETED_BY';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE murm_post
            ADD CONSTRAINT fk_murm_post_deleted_by
            FOREIGN KEY (deleted_by_user_id)
            REFERENCES murm_user (id)
        ';
    END IF;
END;
/


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_tables
    WHERE table_name = 'MURM_EMAIL_VERIFICATION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE murm_email_verification
            (
                id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                                   CONSTRAINT pk_murm_email_verification PRIMARY KEY,
                user_id            NUMBER        NOT NULL,
                token_hash         VARCHAR2(500) NOT NULL,
                expires_at         TIMESTAMP     NOT NULL,
                verified_at        TIMESTAMP,
                created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                CONSTRAINT fk_murm_email_verification_user
                    FOREIGN KEY (user_id)
                    REFERENCES murm_user (id),

                CONSTRAINT uk_murm_email_verification_token
                    UNIQUE (token_hash)
            )
        ';
    END IF;
END;
/


CREATE OR REPLACE TRIGGER tg_murm_share_aiud
    AFTER INSERT OR DELETE
    ON murm_share
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE murm_post
        SET share_count = share_count + 1
        WHERE id = :new.post_id;
    ELSIF DELETING THEN
        UPDATE murm_post
        SET share_count = GREATEST(share_count - 1, 0)
        WHERE id = :old.post_id;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER tg_murm_share_ai';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN
            RAISE;
        END IF;
END;
/


DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_indexes
    WHERE index_name = 'IX_MURM_POST_DELETED_BY';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE INDEX ix_murm_post_deleted_by
            ON murm_post (deleted_by_user_id)
        ';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_indexes
    WHERE index_name = 'IX_MURM_EMAIL_VERIF_USER';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE INDEX ix_murm_email_verif_user
            ON murm_email_verification (user_id, expires_at)
        ';
    END IF;
END;
/

SELECT table_name
FROM user_tables
WHERE table_name IN
(
    'MURM_USER',
    'MURM_POST',
    'MURM_VOTE',
    'MURM_SHARE',
    'MURM_SESSION',
    'MURM_PASSWORD_RESET',
    'MURM_EMAIL_VERIFICATION'
)
ORDER BY table_name;

SELECT table_name,
       column_name,
       data_type,
       nullable
FROM user_tab_columns
WHERE table_name IN ('MURM_USER', 'MURM_POST')
  AND column_name IN
(
    'PASSWORD_CHANGED_AT',
    'THEME_CODE',
    'DELETED_AT',
    'DELETED_BY_USER_ID',
    'MODERATED_AT',
    'MODERATION_REASON'
)
ORDER BY table_name,
         column_id;
