CREATE TABLE murm_direct
(
    id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_murm_direct PRIMARY KEY,
    sender_user_id     NUMBER         NOT NULL,
    recipient_user_id  NUMBER         NOT NULL,
    contents           VARCHAR2(1000) NOT NULL,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    read_at            TIMESTAMP,

    CONSTRAINT fk_murm_direct_sender FOREIGN KEY (sender_user_id) REFERENCES murm_user (id),
    CONSTRAINT fk_murm_direct_recipient FOREIGN KEY (recipient_user_id) REFERENCES murm_user (id),
    CONSTRAINT ck_murm_direct_users CHECK (sender_user_id <> recipient_user_id)
);

CREATE INDEX ix_murm_direct_recipient
    ON murm_direct (recipient_user_id, read_at, created_at);

CREATE INDEX ix_murm_direct_pair
    ON murm_direct (sender_user_id, recipient_user_id, created_at);

CREATE OR REPLACE VIEW vw_murm_direct_conversation AS
WITH participants AS
(
    SELECT sender_user_id AS user_id,
           recipient_user_id AS other_user_id,
           id,
           contents,
           created_at,
           0 AS unread
      FROM murm_direct
    UNION ALL
    SELECT recipient_user_id AS user_id,
           sender_user_id AS other_user_id,
           id,
           contents,
           created_at,
           CASE WHEN read_at IS NULL THEN 1 ELSE 0 END AS unread
      FROM murm_direct
), ranked AS
(
    SELECT p.*,
           ROW_NUMBER() OVER
           (
               PARTITION BY user_id, other_user_id
               ORDER BY created_at DESC, id DESC
           ) AS rn,
           SUM(unread) OVER
           (
               PARTITION BY user_id, other_user_id
           ) AS unread_count
      FROM participants p
)
SELECT r.user_id,
       r.other_user_id,
       u.username,
       r.contents AS last_message,
       r.created_at AS last_at,
       r.unread_count
  FROM ranked r
  JOIN murm_user u
    ON u.id = r.other_user_id
 WHERE r.rn = 1;
