-- DROP TABLE murm_password_reset CASCADE CONSTRAINTS;
CREATE TABLE murm_password_reset
(
    id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_murm_password_reset PRIMARY KEY,
    user_id            NUMBER        NOT NULL,
    token_hash         VARCHAR2(500) NOT NULL,
    expires_at         TIMESTAMP     NOT NULL,
    used_at            TIMESTAMP,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_murm_password_reset_user FOREIGN KEY (user_id) REFERENCES murm_user (id),
    CONSTRAINT uk_murm_password_reset_token UNIQUE (token_hash)
);
