-- DROP TABLE murm_vote CASCADE CONSTRAINTS;
CREATE TABLE murm_vote
(
    id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_murm_vote PRIMARY KEY,
    post_id            NUMBER      NOT NULL,
    user_id            NUMBER      NOT NULL,
    vote_value         NUMBER(1)   NOT NULL,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP,

    CONSTRAINT fk_murm_vote_post FOREIGN KEY (post_id) REFERENCES murm_post (id),
    CONSTRAINT fk_murm_vote_user FOREIGN KEY (user_id) REFERENCES murm_user (id),
    CONSTRAINT uk_murm_vote_once UNIQUE (post_id, user_id),
    CONSTRAINT ck_murm_vote_value CHECK (vote_value IN (-1, 1))
);
