-- DROP TABLE murm_share CASCADE CONSTRAINTS;
CREATE TABLE murm_share
(
    id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_murm_share PRIMARY KEY,
    post_id            NUMBER       NOT NULL,
    user_id            NUMBER,
    share_type         VARCHAR2(20) DEFAULT 'link' NOT NULL,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_murm_share_post FOREIGN KEY (post_id) REFERENCES murm_post (id),
    CONSTRAINT fk_murm_share_user FOREIGN KEY (user_id) REFERENCES murm_user (id),
    CONSTRAINT ck_murm_share_type CHECK (share_type IN ('link', 'native', 'repost'))
);
