-- DROP TABLE murm_user CASCADE CONSTRAINTS;
CREATE TABLE murm_user
(
    id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_murm_user PRIMARY KEY,
    username           VARCHAR2(30)        NOT NULL,
    email              VARCHAR2(320)       NOT NULL,
    password_hash      VARCHAR2(500),
    google_sub         VARCHAR2(255),
    bio                VARCHAR2(180),
    avatar_url         VARCHAR2(1000),
    language_code      VARCHAR2(10) DEFAULT 'pt-BR' NOT NULL,
    email_verified     NUMBER(1)    DEFAULT 0       NOT NULL,
    active             NUMBER(1)    DEFAULT 1       NOT NULL,
    created_at         TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP,

    CONSTRAINT uk_murm_user_username UNIQUE (username),
    CONSTRAINT uk_murm_user_email UNIQUE (email),
    CONSTRAINT uk_murm_user_google_sub UNIQUE (google_sub),
    CONSTRAINT ck_murm_user_language CHECK (language_code IN ('pt-BR', 'en')),
    CONSTRAINT ck_murm_user_email_verified CHECK (email_verified IN (0, 1)),
    CONSTRAINT ck_murm_user_active CHECK (active IN (0, 1))
);
