-- DROP TABLE murm_session CASCADE CONSTRAINTS;
CREATE TABLE murm_session
(
    id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_murm_session PRIMARY KEY,
    user_id            NUMBER         NOT NULL,
    token_hash         VARCHAR2(500)  NOT NULL,
    provider           VARCHAR2(20)   NOT NULL,
    expires_at         TIMESTAMP      NOT NULL,
    revoked_at         TIMESTAMP,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ip_address         VARCHAR2(45),
    user_agent         VARCHAR2(1000),

    CONSTRAINT fk_murm_session_user FOREIGN KEY (user_id) REFERENCES murm_user (id),
    CONSTRAINT uk_murm_session_token UNIQUE (token_hash),
    CONSTRAINT ck_murm_session_provider CHECK (provider IN ('password', 'google'))
);
