-- DROP TABLE murm_post CASCADE CONSTRAINTS;
CREATE TABLE murm_post
(
    id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_murm_post PRIMARY KEY,
    user_id            NUMBER         NOT NULL,
    parent_post_id     NUMBER,
    repost_post_id     NUMBER,
    contents           VARCHAR2(1000) NOT NULL,
    positive_count     NUMBER DEFAULT 0 NOT NULL,
    negative_count     NUMBER DEFAULT 0 NOT NULL,
    share_count        NUMBER DEFAULT 0 NOT NULL,
    status             VARCHAR2(20) DEFAULT 'published' NOT NULL,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP,

    CONSTRAINT fk_murm_post_user FOREIGN KEY (user_id) REFERENCES murm_user (id),
    CONSTRAINT fk_murm_post_parent FOREIGN KEY (parent_post_id) REFERENCES murm_post (id),
    CONSTRAINT fk_murm_post_repost FOREIGN KEY (repost_post_id) REFERENCES murm_post (id),
    CONSTRAINT ck_murm_post_status CHECK (status IN ('published', 'deleted', 'moderated')),
    CONSTRAINT ck_murm_post_positive CHECK (positive_count >= 0),
    CONSTRAINT ck_murm_post_negative CHECK (negative_count >= 0),
    CONSTRAINT ck_murm_post_share CHECK (share_count >= 0)
);
