create sequence DBTOOLS$EXECUTION_HISTORY_SEQ
/

create table DBTOOLS$EXECUTION_HISTORY
(
    ID         NUMBER not null
        constraint DBTOOLS$EXECUTION_HISTORY_PK
            primary key,
    HASH       CLOB,
    CREATED_BY VARCHAR2(255),
    CREATED_ON TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY VARCHAR2(255),
    UPDATED_ON TIMESTAMP(6) WITH TIME ZONE,
    STATEMENT  CLOB,
    TIMES      NUMBER
)
/

create table MURM_USER
(
    ID             NUMBER       default "MURMDB"."ISEQ$$_290434".nextval generated by default on null as identity
		constraint PK_MURM_USER
			primary key,
    USERNAME       VARCHAR2(30)                      not null
        constraint UK_MURM_USER_USERNAME
            unique,
    EMAIL          VARCHAR2(320)                     not null
        constraint UK_MURM_USER_EMAIL
            unique,
    PASSWORD_HASH  VARCHAR2(500),
    GOOGLE_SUB     VARCHAR2(255)
        constraint UK_MURM_USER_GOOGLE_SUB
            unique,
    BIO            VARCHAR2(180),
    AVATAR_URL     VARCHAR2(1000),
    LANGUAGE_CODE  VARCHAR2(10) default 'pt-BR'      not null
        constraint CK_MURM_USER_LANGUAGE
            check (language_code IN ('pt-BR', 'en')),
    EMAIL_VERIFIED NUMBER(1)    default 0            not null
        constraint CK_MURM_USER_EMAIL_VERIFIED
            check (email_verified IN (0, 1)),
    ACTIVE         NUMBER(1)    default 1            not null
        constraint CK_MURM_USER_ACTIVE
            check (active IN (0, 1)),
    CREATED_AT     TIMESTAMP(6) default SYSTIMESTAMP not null,
    UPDATED_AT     TIMESTAMP(6)
)
/

create table MURM_PASSWORD_RESET
(
    ID         NUMBER       default "MURMDB"."ISEQ$$_290441".nextval generated by default on null as identity
		constraint PK_MURM_PASSWORD_RESET
			primary key,
    USER_ID    NUMBER                            not null
        constraint FK_MURM_PASSWORD_RESET_USER
            references MURM_USER,
    TOKEN_HASH VARCHAR2(500)                     not null
        constraint UK_MURM_PASSWORD_RESET_TOKEN
            unique,
    EXPIRES_AT TIMESTAMP(6)                      not null,
    USED_AT    TIMESTAMP(6),
    CREATED_AT TIMESTAMP(6) default SYSTIMESTAMP not null
)
/

create table MURM_POST
(
    ID             NUMBER       default "MURMDB"."ISEQ$$_290445".nextval generated by default on null as identity
		constraint PK_MURM_POST
			primary key,
    USER_ID        NUMBER                            not null
        constraint FK_MURM_POST_USER
            references MURM_USER,
    PARENT_POST_ID NUMBER
        constraint FK_MURM_POST_PARENT
            references MURM_POST,
    REPOST_POST_ID NUMBER
        constraint FK_MURM_POST_REPOST
            references MURM_POST,
    CONTENTS       VARCHAR2(1000)                    not null,
    POSITIVE_COUNT NUMBER       default 0            not null
        constraint CK_MURM_POST_POSITIVE
            check (positive_count >= 0),
    NEGATIVE_COUNT NUMBER       default 0            not null
        constraint CK_MURM_POST_NEGATIVE
            check (negative_count >= 0),
    SHARE_COUNT    NUMBER       default 0            not null
        constraint CK_MURM_POST_SHARE
            check (share_count >= 0),
    STATUS         VARCHAR2(20) default 'published'  not null
        constraint CK_MURM_POST_STATUS
            check (status IN ('published', 'deleted', 'moderated')),
    CREATED_AT     TIMESTAMP(6) default SYSTIMESTAMP not null,
    UPDATED_AT     TIMESTAMP(6)
)
/

create index IX_MURM_POST_USER_CREATED
    on MURM_POST (USER_ID asc, CREATED_AT desc)
/

create index IX_MURM_POST_PARENT_CREATED
    on MURM_POST (PARENT_POST_ID, CREATED_AT)
/

create index IX_MURM_POST_STATUS_CREATED
    on MURM_POST (STATUS asc, CREATED_AT desc)
/

create table MURM_SESSION
(
    ID         NUMBER       default "MURMDB"."ISEQ$$_290448".nextval generated by default on null as identity
		constraint PK_MURM_SESSION
			primary key,
    USER_ID    NUMBER                            not null
        constraint FK_MURM_SESSION_USER
            references MURM_USER,
    TOKEN_HASH VARCHAR2(500)                     not null
        constraint UK_MURM_SESSION_TOKEN
            unique,
    PROVIDER   VARCHAR2(20)                      not null
        constraint CK_MURM_SESSION_PROVIDER
            check (provider IN ('password', 'google')),
    EXPIRES_AT TIMESTAMP(6)                      not null,
    REVOKED_AT TIMESTAMP(6),
    CREATED_AT TIMESTAMP(6) default SYSTIMESTAMP not null,
    IP_ADDRESS VARCHAR2(45),
    USER_AGENT VARCHAR2(1000)
)
/

create index IX_MURM_SESSION_USER_EXPIRES
    on MURM_SESSION (USER_ID, EXPIRES_AT)
/

create table MURM_SHARE
(
    ID         NUMBER       default "MURMDB"."ISEQ$$_290452".nextval generated by default on null as identity
		constraint PK_MURM_SHARE
			primary key,
    POST_ID    NUMBER                            not null
        constraint FK_MURM_SHARE_POST
            references MURM_POST,
    USER_ID    NUMBER
        constraint FK_MURM_SHARE_USER
            references MURM_USER,
    SHARE_TYPE VARCHAR2(20) default 'link'       not null
        constraint CK_MURM_SHARE_TYPE
            check (share_type IN ('link', 'native', 'repost')),
    CREATED_AT TIMESTAMP(6) default SYSTIMESTAMP not null
)
/

create index IX_MURM_SHARE_POST
    on MURM_SHARE (POST_ID)
/

create table MURM_VOTE
(
    ID         NUMBER       default "MURMDB"."ISEQ$$_290455".nextval generated by default on null as identity
		constraint PK_MURM_VOTE
			primary key,
    POST_ID    NUMBER                            not null
        constraint FK_MURM_VOTE_POST
            references MURM_POST,
    USER_ID    NUMBER                            not null
        constraint FK_MURM_VOTE_USER
            references MURM_USER,
    VOTE_VALUE NUMBER(1)                         not null
        constraint CK_MURM_VOTE_VALUE
            check (vote_value IN (-1, 1)),
    CREATED_AT TIMESTAMP(6) default SYSTIMESTAMP not null,
    UPDATED_AT TIMESTAMP(6),
    constraint UK_MURM_VOTE_ONCE
        unique (POST_ID, USER_ID)
)
/

create index IX_MURM_VOTE_POST
    on MURM_VOTE (POST_ID)
/

create index IX_MURM_VOTE_USER
    on MURM_VOTE (USER_ID)
/

